### ISSUE TITLE
Reference to PyTracking

### ISSUE THREAD

**Issue by martin-danelljan** [Daikenan/LTMU#4]
Hi. 

Great work and solid results! I am happy to see that you are using our [PyTracking](https://github.com/visionml/pytracking) framework. I hope you like it, and we appreciate any comments and suggestions :)

Since you base on our [PyTracking](https://github.com/visionml/pytracking) framework, I would very much appreciate if you can mention this and link to our [PyTracking](https://github.com/visionml/pytracking) in your readme.

Also, I saw in your code that you have separate instances of the [PyTracking](https://github.com/visionml/pytracking) code in the DIMP_MU and DIMP_LTMU folders. Our framework has a quite general support of integrating several trackers into the [PyTracking](https://github.com/visionml/pytracking) framework. So please send me a message if you want tips of how to integrate your trackers, or if you have any feedback to us how we can more easily support trackers like yours.

Best regards,
Martin

**Comment by Daikenan** [comment]
Dear martin.
Thanks for your suggestions, I have added the PyTracking's link in readme.In fact, readme has not completed and many refferences is missing(paper link,code link, model links...),I will complete this part as soon as possible.
Pytracking is a great framework which can indeed support several trackers. In DiMP_MU,I integrate two trackers, DiMP(support meta-updater training) and DiMPMU.I seperate DiMP_LTMU and DiMP mainly because the environment of DiMP_LTMU is much more strict,if the same environment is used, the application of DIMP_MU may be restricted.
I really like the PyTracking framework and I do have some suggestions if you don't mind. For example in 'pytracking/tracker/atom/atom.py' line 225, if the 'def track(self, image, info: dict = None)' can be seperate into 'def localization()', 'def scale_estimation()' and 'def update()',it would be much more efficient  to do some modification such as changing different estimation method,different update strategies.
Best regrads.
kenan

**Comment by Daikenan** [comment]
@martin-danelljan 
Dear martin.

Thanks for your suggestions, I have added the PyTracking's link in readme.In fact, readme has not completed and many refferences is missing(paper link,code link, model links...),I will complete this part as soon as possible.

Pytracking is a great framework which can indeed support several trackers. In DiMP_MU,I integrate two trackers, DiMP(support meta-updater training) and DiMPMU.I seperate DiMP_LTMU and DiMP mainly because the environment of DiMP_LTMU is much more strict,if the same environment is used, the application of DIMP_MU may be restricted.

I really like the PyTracking framework and I do have some suggestions if you don't mind. For example in 'pytracking/tracker/atom/atom.py' line 225, if the 'def track(self, image, info: dict = None)' can be seperate into 'def localization()', 'def scale_estimation()' and 'def update()',it would be much more efficient to do some modification such as changing different estimation method,different update strategies.

Best regrads.
kenan

**Comment by martin-danelljan** [comment]
Hi Kenan,

Great, thanks. I also agree. basically the `track()` function can call other functions (there are already some). So the code can be organized into localization and update.

Regards,
Martin
